### ISSUE TITLE
Graphic Display

### ISSUE THREAD

**Issue by chrisdaloa** [Sergey1560/Marlin_FB4S#14]
Hi, Is it possible to set up a graphic layout to the TFT, similar to MKS or firmware stock? The TFT_COLOR_UI options has poor usability with touch. Thanks.

You are doing a great job guys :)

**Comment by Chazy12** [comment]
This is not an issue.
You've to build by yourself.

**Comment by chrisdaloa** [comment]
> 
> 
> This is not an issue.
> You've to build by yourself.

I'have done it, thanks.
