### ISSUE TITLE
Не работает поддержка ESP3D

### ISSUE THREAD

**Issue by XcLxAd** [Sergey1560/Marlin_FB4S#17]
При комментировании //#define MKS_WIFI модуль [ESP3D](https://github.com/luc-github/ESP3D) взаимодействует с принтером не полностью, например, команды перемещения и т.п. выполняются, в статусе на дисплее индицируется IP адрес, но не работает взаимодействие с SD картой. Как исправить эту проблему?

**Comment by Sergey1560** [comment]
Этот вариант Marlin сделан для работы с модулем от МКС. Для этого пришлось в оригинальный код добавить функции работы с MKS WIFI. Для работы ESP3D все это не требуется, поэтому возьмите код с [официального репозитория Marlin](https://github.com/MarlinFirmware/Marlin). 

Весь код который я добавлял (или большая его часть) обернуты в #ifdef MKS_WIFI. Но сделано это скорее для того, чтобы эти "вставки" было легко найти. Нет никакого смысла использовать мою прошивку с ESP3D - вам нужно будет убрать все, что я добавлял. Поэтому логичнее использовать не измененный код Marlin. Если у вас плата robin_nano, вы можете использовать мою конфигурацию просто как образец.
