### ISSUE TITLE
 #define TFT_LVGL_UI не собираетьсЯ ошибка

### ISSUE THREAD

**Issue by girs1982** [Sergey1560/Marlin_FB4S#18]
все по инструкции сделал ошибка про память , на ом что по середине все собралось, но этим пользоваться после стока абсолютное не комильфо
инструкция:
https://sergey1560.github.io/fb4s_howto/mks_ui/

ошибка
/users/gansta/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio\build\mks_robin_nano35\firmware.elf section `.bss' will not fit in region `ram'      
c:/users/gansta/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: region `ram' overflowed by 10744 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\mks_robin_nano35\firmware.elf] Error 1

**Comment by Sergey1560** [comment]
region `ram' overflowed by 10744 bytes  - у вас для не хватило 10744 байт памяти. 
Я надеюсь, вы обратили внимание, что использовать нужно Marlin с официального репозитория, без моих правок для MKS WIFI модуля. 
Для того, чтобы этот интерфейс поместился в памяти, нужно отключить какие-то из функций прошивки. Какие именно - на ваш выбор. Кроме того,  можно уменьшить размер видео буфера. Это описано по ссылке, которую вы привели.

Так же, вы можете попробовать [вариант от MKS](https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware). По-умолчанию там конфигурация для Robin Nano 2.0, с экраном подключенным по SPI. Для работы на Robin Nano 1.* нужно изменить установку "BOARD" и тип экрана.
