### ISSUE TITLE
New release date/ new build

### ISSUE THREAD

**Issue by adripo** [Sergey1560/Marlin_FB4S#2]
Hello, I am using this firmware since 2 weeks ago, but I was experiencing random head movements or extuder going back and forth randomly in the middle of a print. I saw that you fixed this problem with the latest commits. Could you also build the firmware with these edits? Or could you release a new version with the built firmware please?

Thank you

**Comment by Sergey1560** [comment]
I updated the binary to the current state. But I recommend that you build the firmware from the source code.

**Comment by adripo** [comment]
Thank you
