### ISSUE TITLE
Русский язык не поддерживается?

### ISSUE THREAD

**Issue by Engi23** [Sergey1560/Marlin_FB4S#20]
Вместо русского языка кракозяблики

**Comment by Sergey1560** [comment]
На данный момент для варианта интерфейса TFT_COLOR_UI не поддерживается. В шрифте нет кириллических символов. 
В интерфейсе TFT_CLASSIC_UI поддержка русского языка есть.

**Comment by Engi23** [comment]
Да меня интересует TFT_COLOR_UI Это же точечный дисплей, значит шрифт должен быть набором массивов точек. Может добавить? Шрифт же в отдельном файле лежит? Если дадите пример как зашифровать 1 букву, думаю я смогу сделать для остальных.

**Comment by Sergey1560** [comment]
Пример шрифта - Marlin/src/lcd/tft/fontdata/helvetica_18.cpp
В комментариях там описано, в каком виде лежит массив.
Есть еще одно небольшое ограничение - марлин использует максимум 255 символов.

**Comment by Engi23** [comment]
Вот этот файл. https://github.com/Sergey1560/Marlin_FB4S/blob/FB4S_WIFI/Marlin/src/lcd/tft/fontdata/helvetica_18.cpp к сожалению не могу понять как символы закодированны в массиве. Похоже разные буквы занимают разный объем, какой там символ разделитель и как закодированы пиксели?

**Comment by Sergey1560** [comment]
Описание структуры font_t находится в Marlin/src/lcd/tft/tft_string.h

**Comment by Engi23** [comment]
TFT_CLASSIC_UI поддерживает сенсорный ввод?

**Comment by Sergey1560** [comment]
> TFT_CLASSIC_UI поддерживает сенсорный ввод?

Да, поддерживает.
