### ISSUE TITLE
Не прошивает модуль wifi

### ISSUE THREAD

**Issue by Kost38** [Sergey1560/Marlin_FB4S#23]
Прошивка из релиза не прошивает модуль wi-fi. Нет никакой реакции при загрузке на файл MksWifi.bin на карточке. Файл пробовал разный, 300 кб и 4 мб.

**Comment by Sergey1560** [comment]
В прошивке на данный момент нет загрузчика для esp модуля. На практике, он не очень нужен. Стандартный модуль уже прошит и необходимости менять в нем прошивку не возникает. В случае установки самодельного модуля, его проще прошить "на столе", до установки в плату. Эта функция была не очень нужна и я ее не реализовывал.
Прошить модуль, при необходимости, можно через стандартную прошивку.

Судя по коммитам в bugfix ветку, МКС добавляет к своему интерфейсу поддержку WIFI модуля. В том числе и обновление прошивки в нем. Таким образом, в скором времени можно ожидать поддержку этого в стабильной ветке Marlin.

**Comment by Kost38** [comment]
Спасибо за объяснение, теперь все понятно.
