### ISSUE TITLE
буква ё не отображается

### ISSUE THREAD

**Issue by Engi23** [Sergey1560/Marlin_FB4S#26]
Я понимаю что не очень важный момент, но и поправить не сложно если знать где...
буква ё отображается как каракули, видел в меню О принтерере "Счётчик печати"

**Comment by Sergey1560** [comment]
Работа на отображением русского языка пока не закончена. Как временное решение, вы можете исправить "ё" на "е". Или присоединиться к работе - https://github.com/Sergey1560/Marlin_FB4S/pull/25

**Comment by Sergey1560** [comment]
Исправлено.
