### ISSUE TITLE
 включение  #define BABYSTEP_DISPLAY_TOTAL приводит к ошибке

### ISSUE THREAD

**Issue by Engi23** [Sergey1560/Marlin_FB4S#27]
включение  #define BABYSTEP_DISPLAY_TOTAL приводит к предупреждениям во время компиляции, а собственно попытка зайти туда после компиляции приводит в синему экрану смерти. Причем на английском языке также

.pio/build/mks_robin_nano35/src/src/lcd/menu/menu_tune.cpp.o: In function `_lcd_babystep(AxisEnum, char const*)':
D:\3D принтер\Прошивка марлин\Marlin_FB4S-FB4S_WIFI/Marlin\src\lcd\menu/menu_tune.cpp:74: warning: undefined reference to `lcd_moveto(unsigned char, unsigned char)'
.pio/build/mks_robin_nano35/src/src/lcd/menu/menu_tune.cpp.o: In function `lcd_put_u8str_P(char const*)':
D:\3D принтер\Прошивка марлин\Marlin_FB4S-FB4S_WIFI/Marlin\src\lcd\menu\../lcdprint.h:149: warning: undefined reference to `lcd_put_u8str_max_P(char const*, unsigned short)'
.pio/build/mks_robin_nano35/src/src/lcd/menu/menu_tune.cpp.o: In function `lcd_put_wchar(unsigned long)':
D:\3D принтер\Прошивка марлин\Marlin_FB4S-FB4S_WIFI/Marlin\src\lcd\menu\../lcdprint.h:167: warning: undefined reference to `lcd_put_wchar_max(unsigned long, unsigned short)'
.pio/build/mks_robin_nano35/src/src/lcd/menu/menu_tune.cpp.o: In function `lcd_put_u8str(char const*)':
D:\3D принтер\Прошивка марлин\Marlin_FB4S-FB4S_WIFI/Marlin\src\lcd\menu\../lcdprint.h:161: warning: undefined reference to `lcd_put_u8str_max(char const*, unsigned short)'

**Comment by Sergey1560** [comment]
Это проблема в реализации COLOR UI. На данный момент BABYSTEP_DISPLAY_TOTAL не поддерживается с этим интерфейсом. Сам функционал babystepping при этом работает.
