### ISSUE TITLE
#define PROBE_OFFSET_WIZARD + русский язык не работают вместе

### ISSUE THREAD

**Issue by Engi23** [Sergey1560/Marlin_FB4S#28]
#define PROBE_OFFSET_WIZARD + русский язык не работают вместе
при компиляции возникают предупреждения, при их игнорированнии функция работает неправильно, вылетает после первого нажатия далее
Marlin\src\lcd\menu\menu_probe_offset.cpp: In function 'void probe_offset_wizard_menu()':
Marlin\src\lcd\menu\menu_probe_offset.cpp:77:6: warning: 'РјРј' directive writing 4 bytes into a region of size 3 [-Wformat-overflow=]
 void probe_offset_wizard_menu() {
      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/WString.h:29:0,
                 from C:\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/wirish.h:47,
                 from C:\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/Arduino.h:30,
                 from Marlin\src\lcd\menu\../../inc/../HAL/./STM32F1/../shared/Marduino.h:36,
                 from Marlin\src\lcd\menu\../../inc/../HAL/./STM32F1/HAL.h:32,
                 from Marlin\src\lcd\menu\../../inc/../HAL/HAL.h:26,
                 from Marlin\src\lcd\menu\../../inc/MarlinConfig.h:31,
                 from Marlin\src\lcd\menu\../ultralcd.h:24,
                 from Marlin\src\lcd\menu\menu.h:24,
                 from Marlin\src\lcd\menu\menu_item.h:24,
                 from Marlin\src\lcd\menu\menu_probe_offset.cpp:37:
C:\.platformio\packages\framework-arduinoststm32-maple\STM32F1\cores\maple/avr/pgmspace.h:28:37: note: 'sprintf' output 22 or more bytes into a destination of size 20
 #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)
                              ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
Marlin\src\lcd\menu\menu_probe_offset.cpp:95:5: note: in expansion of macro 'sprintf_P'
     sprintf_P(tmp, GET_TEXT(MSG_MOVE_Z_DIST), dtostrf(SHORT_MANUAL_Z_MOVE, 1, digs, numstr));

**Comment by Sergey1560** [comment]
PROBE_WIZARD в данный момент в COLOR_UI не поддерживается.
https://github.com/Sergey1560/Marlin_FB4S/issues/21

Отображение русского языка в COLOR UI работает, но реализовано пока не до конца.
