### ISSUE TITLE
Не работает выгрузка филамента

### ISSUE THREAD

**Issue by Ustinych** [Sergey1560/Marlin_FB4S#29]
Не работает выгрузка филамента

**Comment by Sergey1560** [comment]
Будьте добры, немного подробностей.

**Comment by Ustinych** [comment]
Когда в меню выбираешь выгрузить филамент, принтер вытягивает пруток примерно на 30 мм и сразу втягивает его обратно. В релизных прошивках такого  не было.

**Comment by Engi23** [comment]
а не забыли ли вы правильно настроить датчик филамента? например инвертировать его состояние. Очень похоже на что то такое

**Comment by Ustinych** [comment]
Датчик филамента настроен корректно. В настройках изменил параметр #define FIL_RUNOUT_STATE на LOW

**Comment by Sergey1560** [comment]
> Датчик филамента настроен корректно. В настройках изменил параметр #define FIL_RUNOUT_STATE на LOW

Настройка датчика филамента зависит от конкретной модели принтера. Для FB4S и FB5 это значение отличается. В конфигурации стоит значение для FB4S.
