### ISSUE TITLE
Некорректно работает датчик окончания филамента на FB G5

### ISSUE THREAD

**Issue by Ustinych** [Sergey1560/Marlin_FB4S#30]
Не работает датчик окончания филамента на FB G5.
Для корректной работы, необходимо изменить параметр #define FIL_RUNOUT_STATE  на   LOW

**Comment by Sergey1560** [comment]
А на FB4S нужно значение FIL_RUNOUT_STATE HIGH. 
В готовых сборках в будущем исправлю, в коде останется как есть.
