### ISSUE TITLE
warning: Calling missing SConscript without error is deprecated

### ISSUE THREAD

**Issue by Shliskenstickin** [Sergey1560/Marlin_FB4S#32]
При начале компиляции:

_warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript 'buildroot\share\PlatformIO\scripts\common-dependencies-post.py'
File "C:\users\death\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 185, in <module>_

В ходе экспериментов заменил папку buildroot из репозитория оригинального марлина и сообщение в начале ушло.

На сколько это сообщение критично может стоит оттуда папку подтянуть?

**Comment by Sergey1560** [comment]
> При начале компиляции:
> 
> _warning: Calling missing SConscript without error is deprecated. Transition by adding must_exist=0 to SConscript calls. Missing SConscript 'buildroot\share\PlatformIO\scripts\common-dependencies-post.py' File "C:\users\death.platformio\penv\lib\site-packages\platformio\builder\main.py", line 185, in _
> 
> В ходе экспериментов заменил папку buildroot из репозитория оригинального марлина и сообщение в начале ушло.
> 
> На сколько это сообщение критично может стоит оттуда папку подтянуть?

Насколько я понимаю, проблема связана с тем, что папка buildroot по какой-то причине внесена в gitignore с комментарием "# Windows users need this to prevent adding build tree to git" Т.е. она не отслеживалась и не обновлялась.
Я обновил папку в проекте, и так же обновил gitignore.
