### ISSUE TITLE
Отключение пищалки (buzzer)

### ISSUE THREAD

**Issue by grishastaver** [Sergey1560/Marlin_FB4S#34]
Приветствую!

Подскажи пожалуйста, есть ли какая-то возможность полностью отключить пищалку-buzzer на FBG5?

**Comment by Sergey1560** [comment]
Добрый день.
Я думаю самый простой вариант, просто закомментировать определение для ноги управляющей пищалкой.
В Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h закомментируте #define BEEPER_PIN :

```
//
// LCD / Controller
//
//#define BEEPER_PIN                          PC5
```

**Comment by grishastaver** [comment]
Закомментил, но при включении пищание все равно осталось. Видимо, идет команда еще до загрузки прошивки и это не вылечить программно :( В любом случае, спасибо!
