### ISSUE TITLE
Time Left Issue

### ISSUE THREAD

**Issue by Ilya-Pak** [Sergey1560/Marlin_FB4S#36]
Может кто-нибудь сталкивался? Время на принтере все время  00:00:01.
Прошивка MKS_ROBIN_NANO_MARLIN 2.0
Может ли Сторожевой ТАймер влиять на это... Просто в коде не отыскал их связи.

**Comment by Sergey1560** [comment]
Сторожевой таймер на это влиять никак не может, он с этим совершенно не связан.
На это возможно может влиять функция [Set Print Progress](https://marlinfw.org/docs/gcode/M073.html), но точно ответить затрудняюсь. Нужно смотреть в gcode, есть ли там команды управления прогрессом печати. 
Так же можно попробовать выключить LCD_SET_PROGRESS_MANUALLY.
В 2.0.8 есть поддержка USE_M73_REMAINING_TIME. Если слайсер добавляет в код команды M73, будет отображаться оставшееся время из расчетов слайсера, а не прошивки.
