### ISSUE TITLE
Stuck updating 100%

### ISSUE THREAD

**Issue by Nikolay1243** [Sergey1560/Marlin_FB4S#40]
hi, I've tried to install your firmware on my ghost 5 but the update process stops at a screen saying "updating 100%" and then i have to reflash the stock firmware to get the printer to start normally again. Can you help?

**Comment by Sergey1560** [comment]
Which file are you copying to the memory card and which card is installed in your printer?

**Comment by Nikolay1243** [comment]
Sorry I didn't give more details. I have the newest mainboard named robin nano-s v1.3. i posted about it on the telegram group and the members told me your firmware isn't for that board.
