### ISSUE TITLE
Нет SD карты

### ISSUE THREAD

**Issue by Ustinych** [Sergey1560/Marlin_FB4S#41]
Привет!
Установил  Marlin 2.0.8.1 из последнего релиза на Flying bear Ghost 5. При включении принтера не определяется SD карта. В меню пишет нет SD карты.  Помогло добавление в Configuration_adv строки #define STARTUP_COMMANDS "M21".

**Comment by Sergey1560** [comment]
Устанавливали бинарник (какой?) или сами собирали?

**Comment by Ustinych** [comment]
Собрал из https://github.com/Sergey1560/Marlin_FB4S/archive/refs/tags/2.0.8.1.zip

**Comment by Ustinych** [comment]
[config.zip](https://github.com/Sergey1560/Marlin_FB4S/files/6560323/config.zip)
 Мои конфигурационные файлы

**Comment by Sergey1560** [comment]
Отключите #define SD_DETECT_STATE HIGH

**Comment by Ustinych** [comment]
Спасибо, помогло.
