### ISSUE TITLE
[BUG] (WIFI garbage)

### ISSUE THREAD

**Issue by anufrievmax** [Sergey1560/Marlin_FB4S#43]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

WiFi работает, но при подключении по порту 8080 в терминале с периодичностью около раза в секунду всплывают ответы от принтера на команды, которые никто не шлёт, нет больше хостов. Причем скрипты  типа report progress и тому подобное хост не активировал. Слать ответы на порт начинает сразу после подключения к сокету. Ответы в стиле "ok" и переход на след строку. Причем плагин Cura работает. Как побороть? Хочется откалибровать bltouch через терминал, а не получается. Спасибо! 
![Снимок](https://user-images.githubusercontent.com/87042113/124729652-50573100-df19-11eb-8183-eeda227c03c5.JPG)

### Version of Marlin Firmware

2.x

### Printer model

FBG5

### Your Slicer

Cura

**Comment by Sergey1560** [comment]
Для более удобного отображения включите в Putty на закладке Terminal опции "Implict CR in every LF" и "Implict LF in every CR", будут нормально работать переносы строк.
То, что вы посчитали мусором - ответы на команды которые шлет сам wifi модуль. Сам модуль, без подключения к нему, примерно раз в секунду шлет команды M991 (запрос температур),  M997 (запрос состояния принтера),  M27 (запрос прогресса печати). Команды эти идут от wifi модуля и ответы на них соответственно обратно.

Варианты решения:
1. Изменить прошивку wifi модуля
2. Игнорировать выдачу этих сообщений
3. Использовать для настройки терминал при подключении по USB
