### ISSUE TITLE
2.0.9.1 Не хочет загружаться при подключенной SD

### ISSUE THREAD

**Issue by KEHT067** [Sergey1560/Marlin_FB4S#47]
### Bug Description

Здравствуйте!
FB Ghost 5, с платой mks robin nano 1.** (старой)
Столкнулся с проблемой после обновления на 2.0.9.1
Marlin самосбор на основе Вашего, добавил bltouch, ubl. Данные по bltouch и корпус напечатал отсюда:
https://www.thingiverse.com/thing:4824897.
В итоге после перепрошивки, появляется лого Marlin гаснет экран и перезагрузка. Опытным путем выяснил, что после извлечения sd карты marlin все же загружается и работает, если sd карту снова вставить и попытаться отправить файл с куры - принтер зависает.
Во вложении мой конфиг [Config.zip](https://github.com/Sergey1560/Marlin_FB4S/files/7220519/Config.zip), буду безумно благодарен советам что я делаю не так.
Спасибо

**Comment by Sergey1560** [comment]
https://github.com/Sergey1560/Marlin_FB4S/issues/49
