### ISSUE TITLE
п

### ISSUE THREAD

**Issue by malysh28** [Sergey1560/Marlin_FB4S#50]
### Is your feature request related to a problem? Please describe.

Привет а как на счет новой платы mks_robin_nano_v1_3 , марлин ее поддерживает ?
там 2 драйвера 2208 и 2 драйвера 4988 но проц уже 407

### Describe the feature you want

работает с новой платой ?

**Comment by malysh28** [comment]
https://drive.google.com/file/d/14pzZzLJJyv7V-NUTVTPvgkVzV44GzCvT/view?usp=sharing

**Comment by Sergey1560** [comment]
Добрый день.
Поддерживает, все настройки аналогичны Robin Nano-s v1.3. Что и как нужно изменить описано в readme.

**Comment by malysh28** [comment]
> Добрый день. Поддерживает, все настройки аналогичны Robin Nano-s v1.3. Что и как нужно изменить описано в readme.

Спасибо вам за вашу работу )

Как я понимаю нужно только поменять драйвера в прошивке? Ведь в s 1.3 стоят 2225
