### ISSUE TITLE
doesn't see endstop when parking at home

### ISSUE THREAD

**Issue by CoolRinat** [Sergey1560/Marlin_FB4S#52]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Не видит концевик по оси Y, упирается и пытается двигаться дальше, прошивка собирал сам на основе готовых исходников заменив инверсию и версию материнской платы. Готовая прошивка под mks robin nano s v1.3 не работает, так как неправильная инверсия.

### Version of Marlin Firmware

2.0.9.1

**Comment by Sergey1560** [comment]
В собранных прошивках есть варианты под все основные платы.
Посмотрите как состояние концевика отображается в M119
