### ISSUE TITLE
[FR] Настройка linear advance на экране печати

### ISSUE THREAD

**Issue by feivur** [Sergey1560/Marlin_FB4S#55]
### Describe the feature you want

Хочется иметь возмжность менять linear advance во время печати, как и параметры температуры, например.

**Comment by Sergey1560** [comment]
Такая возможность есть. Во время печати нажмите символ шестеренки, откроется меню настроек. Там есть возможность изменить LA.

**Comment by feivur** [comment]
![Uploading IMG_20211212_215454.jpg…]()

**Comment by feivur** [comment]
Такой возможности нет(.
Зато есть меню замены пластика. Думаю, его не должно быть во время печати.

**Comment by feivur** [comment]
![IMG_20211212_215454_1](https://user-images.githubusercontent.com/12371350/145725675-344916d3-dc6d-4d2a-99a6-57ade9684351.jpg)

**Comment by Sergey1560** [comment]
Не используйте интерфейс от MKS. В классическом COLOR UI эта возможность есть.

**Comment by feivur** [comment]
Я бы рад от него отказаться. Но в классическом плагин в куре не подключается к принтеру по wifi. Пробовал компилировать с и без флага MKS_WIFI_MODULE.
