### ISSUE TITLE
Питание на пине CS

### ISSUE THREAD

**Issue by Esmertec** [Sergey1560/Marlin_FB4S#57]
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

Не совсем баг, но все же. Решил апнуться с прошивки 2.0.7.2 до 2.0.9.2 разумеется. Проблема в том, что у меня стоял модуль автоотключения через релюшку подцепленную на CS = PE5. На 2.0.9.2 принтер вырубается т.к. на этом пине (CS = PE5) нет напряжения. Как его включить обратно? Заранее спасибо за ответ!

### Version of Marlin Firmware

2.0.9.2

### Printer model

FBG5

**Comment by Sergey1560** [comment]
Вам нужно указать SUICIDE_PIN. В 2.0.9 немного иная структура в файлах pins*, общие ноги для robin nano плат вынесли в отдельный файл Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO_common.h
Укажите в файле для вашей платы (например Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h если плата robin nano v1.1) настройки SUICIDE_PIN. Их можно скопировать из 2.0.7

**Comment by Esmertec** [comment]
Спасибо за ответ, попробую сделать. По поводу новой структуры я уже понял, т.к. начиная с 2.0.8.1 пины не работают - проверено xD Отпишусь по результату
P.S. В исходниках еще что-то нужно будет поменять например vref? У меня плата v1.1 (красная flyingbear reborn 2.0), драйвера стоят на x\y 2208, на z и экструдер tmc 2209. Это будет моя первая сборка прошивки под принтак не хотелось бы где-то накосяячить)
