### ISSUE TITLE
Плата Flyingbear Reborn v3.0

### ISSUE THREAD

**Issue by mugabe** [Sergey1560/Marlin_FB4S#59]
FB5 пришёл с такой платой, по компоновке очень похожа на Robin Nano V3.0, но с распаянными драйверами и STM32F**103**.
Подойдёт ли к ней какая-то прошивка (из типовых)?

![272183606_10224355223262506_4671619328728892040_n](https://user-images.githubusercontent.com/475344/150739336-75f438d4-ea51-4672-99e7-b4f1ff73d610.jpg)
![photo_2022-01-24 10 27 06](https://user-images.githubusercontent.com/475344/150739516-7bc05530-7305-4226-9890-5fd6bf72f5db.jpeg)

**Comment by Sergey1560** [comment]
Эта плата больше всего похожа на Robin Nano-s 1.3, только с stm32f103, вместо stm32f407. В схеме Robin Nano-s 1.3 обозначена возможность установки как f407, так и f103.
К этой плате, скорее всего, подойдут прошивки для f103. Единственное, что нужно будет изменить - направления осей. Я думаю, подойдет набор от Robin Nano-s 1.3.

**Comment by Sergey1560** [comment]
Для этой платы подойдет сборка для F103 (mks_robin_nano35 или mks_robin_nano35_maple в platformio)
В configuration.h добавлен набор направлений для осей FB_5_REBORN_3_0

**Comment by Al3eRtO** [comment]
Hi, 
so the right firmware is mks robin nano v1 ( Robin Nano-s 1.3) or v2 (mks_robin_nano35) ?
