### ISSUE TITLE
Marlin 2.0.9.3 fb4s_All_TMC2208

### ISSUE THREAD

**Issue by LieToMe51** [Sergey1560/Marlin_FB4S#62]
Хелп! Перестаёт работать мотор экструдера после 3го слоя - где-то 30 минут печати.
До этого печатал маленькую модель 8-10 минут и все было нормально.
Драйверы настроены на: x - 1.2В; y - 1.2В; z - 1.2В; e - 1.4В. 
![image](https://user-images.githubusercontent.com/98982514/152423498-45f381b1-7904-4945-90e7-11e79a872790.jpg)
В чем может быть причина?!

**Comment by nixprosoft** [comment]
Я думаю, что если Вы приложите G-CODE который крашится, то диагностировать будет проще.

**Comment by Sergey1560** [comment]
Добрый день.
LA используете? С 2208 и 2225 чаще всего проблема в использовании Linear Advance.  Описание проблемы от TMC есть в issue Klipper - https://github.com/Klipper3d/klipper/issues/196#issuecomment-383122655
Если проблема в этом, то можно или переключить драйвер в spreadcycle или использовать 2209.
