### ISSUE TITLE
прошивка марлин для 3д принтера

### ISSUE THREAD

**Issue by kuxoff** [Sergey1560/Marlin_FB4S#65]
друзья помогите собрать прошивку для 3д принтера анет а 8 плюс под материнскую плату mks robin nano v3 у самого не получается компиляция

**Comment by Sergey1560** [comment]
Эта сборка вам не подойдет. MKS Robin Nano v3 (не Reborn 3.0) использует подключение SD карты через SPI. Такое подключение пока мой драйвер не поддерживает. 
Используйте оригинальный Marlin (https://github.com/MarlinFirmware/Marlin). Для работы WIFI модуля вам нужно выбрать графический интерфейс MKS UI. 
Как собрать прошивку, смотрите в видео Дмитрия Соркина (https://www.youtube.com/watch?v=HirIZk0rWOQ)
