### ISSUE TITLE
STM32F103 MKS Robin nano v1.2

### ISSUE THREAD

**Issue by ExsyDev** [Sergey1560/Marlin_FB4S#66]
Привет. Пытаюсь установить готовую сборку: fb_5 - FB5, 2 драйвера A4988, 2 драйвера TMC2225 под плату медведя 5: MKS Robin Nano v1.2 на базе STM32F103. Но почему-то зависает на TFT Updating 100% и дальше не идет после того как пытаюсь установить прошивку на принтере.

Пытался собрать самостоятельно под плату:

`BOARD_MKS_ROBIN_NANO_V2 // MKS Robin Nano V2 (STM32F103VET6)`

Но похоже и она не подходит, поскольку при компиляции выдает ошибку: #error "MKS Robin nano v2 doesn't support FSMC-based TFT displays."

Как быть? Куда копать?
Буду признателен за помощь.

**Comment by Sergey1560** [comment]
Зависание на  TFT Updating 100% как правило связано с неправильным выбором прошивки. Вы загружаете прошивку для другого микроконтроллера, и она не работает. [Вот здесь](https://sergey1560.github.io/fb4s_howto/mks_board/) есть описание плат. 

Если у вас плата MKS Robin Nano v1.2, зачем вы пытаетесь собирать под MKS Robin Nano V2? Эти платы отличаются.
