### ISSUE TITLE
configuration together with firmware

### ISSUE THREAD

**Issue by dmitrychepel** [Sergey1560/Marlin_FB4S#68]
предлагается с каждой прошивкой выкладывать сразу и конфиг файл с помощью которого она обиралась. так будет удобнее вносить модификации.
например сейчас для reborn v3 в директории лежит только firmare

**Comment by Sergey1560** [comment]
На странице релиза, кроме архива с готовыми прошивками, есть архив с исходным кодом, из которого они были собраны.
Разница в конфигурации между платами слишком мала, чтобы выкладывать отдельно - направления драйверов и название платы (для f1 и f4 плат разные).
