### ISSUE TITLE
2.1.1 Reborn v3.0 зависает на "TFT updating 100%".

### ISSUE THREAD

**Issue by AtomHell** [Sergey1560/Marlin_FB4S#72]
Расширение прошивки на карте памяти меняется на *.cur . Карту форматировал SD Card Formatter'ом. Родная прошивка с этой же карты встаёт без проблем. Плата у меня точно reborn v3.0. Одна из предыдущих версий прошивки успешно устанавливалась. Пишу в первый раз, сильно не пинайте, если что не так.

**Comment by 10on** [comment]
Присоединяюсь,  проблема аналогичная.
Откат на предыдущий релиз проходит успешно. 

Если попробовать перезагрузить принтер - экран не работает, репитер хост подключаться не хочет.
Звук включения со спикера есть.

Шил готовой сборкой отсюда

**Comment by AtomHell** [comment]
Пробовал собирать из исходников 2.1.1 mks_robin_nano35 и mks_robin_nano35_maple. И всё равно прошивка не встаёт.

**Comment by Sergey1560** [comment]
Судя по всему, я прошивку для Reborn v3.0 собрал под F4. Собранная под F1 нормально запускается, но есть проблемы с подключением карты памяти. Эта проблема не только на Reborn v3.0.
