### ISSUE TITLE
Ghost 5 with reborn v 3.0 motherboard is not a bootable on 2.1+ versions

### ISSUE THREAD

**Issue by dmitrychepel** [Sergey1560/Marlin_FB4S#75]
Now I have 2.0.9.3_1 version from _releases_ on my ghost 5.
I tryed update to new 2.1.1 version from _releases_ for LA fixes. and I see that TFT update finished (become to 100%) and freeze. after that ghost become to unbootable state. I could revert to 2.0.9.3 but 2.1.1 does not work.
I tryed to change sdcard, tryed to boot without sdcard, and it is not help me.
BTW on the 2.0.9.3 works fine both versions libmaple and st_hal.

**Comment by Sergey1560** [comment]
Судя по всему, сборка для платы reborn v3.0 сделана не под тот тип процессора в бинарниках для 2.1.1

**Comment by dmitrychepel** [comment]
Если что надо попробовать, то могу.

**Comment by ConstantinoGoo** [comment]
> Если что надо попробовать, то могу.

Пробовали обновленную прошивку 2.1.1?

**Comment by dmitrychepel** [comment]
как я понял сообщение удалили, не смог его найти. Но если что версию 2.1.1 августовскую пробовал. более новую, если такая есть, не вижу.

**Comment by ConstantinoGoo** [comment]
> как я понял сообщение удалили, не смог его найти. Но если что версию 2.1.1 августовскую пробовал. более новую, если такая есть, не вижу.

Да, я почему-то подумал, что ставил 2.0.9..., а висит 2.1.1. А потом как понял... Извиняюсь за беспокойство.

**Comment by ConstantinoGoo** [comment]
С 2.1.2 принтер FB Ghost 5 (reborn v.3) запускается и прошивается, но принтер зависает после нажатия зеленой галочки (подтверждение начала печати выбранного файла). Текущую ветку с ошибкой загрузки можно закрывать и открывать новую.
![SCR-20230102-tvs](https://user-images.githubusercontent.com/49076763/210268204-f11fc5ef-720d-46b2-b686-074c5c29ea5c.png)

**Comment by dmitrychepel** [comment]
Теперь Реборн v3 загружается. Эта проблема решена.
