### ISSUE TITLE
Ghost 5 (reborn v 3.0, robin Nano 1.2) motherboard is not able to start printing on 2.1.2+ versions

### ISSUE THREAD

**Issue by ConstantinoGoo** [Sergey1560/Marlin_FB4S#76]
The printer works fine until the green check mark is pressed. Then the printer just freezes

![SCR-20230102-tvs](https://user-images.githubusercontent.com/49076763/210571190-abf6f272-6507-480a-9a16-93b47fa1b10f.png)

https://user-images.githubusercontent.com/49076763/210572595-f379513b-cb35-4057-89b6-7562595564e0.mov

**Comment by BWorkshop** [comment]
У меня аналогичная проблема после прошивки на FBG5 с платой Robin Nano 1.2, зависает после подтверждения выбора файла, РепетирХост выводит Read error. Кроме этого, происходит остановка оси X во время печати, буквально на первом же слое, возможность движения восстанавливается после перезагрузки. На осях X и Y стоят TMC2208. Никак не получается решить.

**Comment by Sergey1560** [comment]
Явно есть какие-то проблемы при работе с картой. Попробуйте готовую прошивку из bugfix. Я в последнем релизе выложил архив. Это ветка bugfix марлина с изменениями только в разделе конфигурации. Весь код ровно тот, что был, без изменений.  Не будет работать wifi, но будет понятно, проблема связана с моими изменениями под wifi модуль, или нет.

**Comment by ConstantinoGoo** [comment]
> Явно есть какие-то проблемы при работе с картой. Попробуйте готовую прошивку из bugfix. Я в последнем релизе выложил архив. Это ветка bugfix марлина с изменениями только в разделе конфигурации. Весь код ровно тот, что был, без изменений. Не будет работать wifi, но будет понятно, проблема связана с моими изменениями под wifi модуль, или нет.

Прошивка .../firmware/bugfix/stm32f103_boards/reborn_v3 в версии 2.1.2_2 прошивается и запускается на печать корректно.

**Comment by BWorkshop** [comment]
После исправления Сергеем 09.01.2023 я установил прошивку из ветки FB4S_WIFI, все стало работать как нужно. SD карта читается, две печати прошли без сбоев по осям.

**Comment by dmitrychepel** [comment]
на reborn v 3.0 на 2.1.2_3 печать все равно виснет. и флешка подглюкивает.

**Comment by ConstantinoGoo** [comment]
В актуальной версии прошивки по состоянию на 13.01.2023 проблема не актуальна.
