### ISSUE TITLE
2.1.2_3. FB5. Reborn v3.0. Остановка движения по оси X.

### ISSUE THREAD

**Issue by ConstantinoGoo** [Sergey1560/Marlin_FB4S#79]
Во время печати экструдер перестаёт передвигаться по оси X, но продолжает печатать. В итоге пластик наплавляется одной стенкой.
Запущено 3 печати, во всех 3 дефект проявился (причём +- в одном и том же месте).

![IMG_7864](https://user-images.githubusercontent.com/49076763/212317380-83ac4318-d083-4bf5-9ce1-b0c717bd9fc4.jpg)

**Comment by Sergey1560** [comment]
Попробуйте готовую сборку из папки bugfix (в 2.1.2_2 были собраны) с этим же gcode-дом.

**Comment by Sergey1560** [comment]
Попробуйте установить тип драйвера TMC2208_STANDALONE для осей, где используется 2208 или 2225. 
Я пересобрал прошивки с указанием типа драйвера.
Возможно, после добавления алгоритма IS, драйвер отключался так же, как при работе с LA. Для 2208 добавили недавно исправление, но оно работает, если указать нужный тип драйвера.
